# GitHub Actions workflow to build and deploy Flask app to Google Cloud Run
name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/eagleies-photobox-system

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy eagleies-photobox-system \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/eagleies-photobox-system \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
